name: 'Publish nightly image'
description: 'Publish image stored as Github Artifact'
inputs:
  DISCORD_WEBHOOK:
    description: 'Publish using Discord webhook'
    required: false
  IMAGE_NAME:
    description: 'Name of image to build'
    required: true
runs:
  using: "composite"
  steps:
  - uses: actions/download-artifact@v2
    with:
      name: ${{ inputs.IMAGE_NAME }}
      path: dist
  - name: Create environment artifacts
    id: packer
    shell: bash
    run: |
      ls dist/
      . dist/${{ inputs.IMAGE_NAME }}.sh
      echo ::set-output name=image_name::"$IMAGE_NAME"
      echo ::set-output name=image_path::"$IMAGE_PATH"
      echo ::set-output name=image_url::"$IMAGE_URL"
      echo ::set-output name=checksum_url::"$CHECKSUM_URL"
      echo ::set-output name=manifest_url::"$MANIFEST_URL"
  - name: Send Discord notification
    env:
      DISCORD_WEBHOOK: ${{ inputs.DISCORD_WEBHOOK }}
    uses: Ilshidur/action-discord@master
    with:
      args: |
        🧪 NEW nightly `${{ steps.packer.outputs.image_name }}`
        ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}