name: 'Publish image to CDN'
description: 'Publish image to CDN via gsutils'
inputs:
  artifact:
    description: 'Name of artifact to download'
    required: true
  service_key:
    description: 'key.json belonging to GCP Service Account'
    required: true
  dest:
    description: 'GCP Storage key to publish artifact under (excluding bucket name)'
    required: true
  bucket:
    description: 'GCP Storage bucket name. Default: print-nanny-cdn'
    required: true

runs:
  using: "composite"
  steps:
  - name: Download source artifact
    uses: actions/download-artifact@v2
    with:
      name: ${{ inputs.artifact }}
      path: src
  - id: 'auth'
    uses: 'google-github-actions/auth@v0'
    with:
        credentials_json: '${{ inputs.service_key }}'
  - name: 'Set up Cloud SDK'
    uses: 'google-github-actions/setup-gcloud@v0'

  - name: Publish Release to CDN
    shell: bash
    id: release
    env:
      PRINTNANNY_API_TOKEN: ${{ inputs.PRINTNANNY_API_TOKEN }}
      PRINTNANNY_API_URL: "https://print-nanny.com"
    run: |
      gsutil rsync src/artifact.tar.gz gs://${{ inputs.bucket}}/${{ inputs.dest }}

  # - name: Send Discord notification
  #   env:
  #     DISCORD_WEBHOOK: ${{ inputs.DISCORD_WEBHOOK }}
  #   uses: Ilshidur/action-discord@master
  #   with:
  #     args: |
  #       💜 New image: `${{ steps.manifest.outputs.image_stamp }}`
  #       [Download](${{ steps.manifest.outputs.image_url }})
  #       [Release Page](${{ steps.release.url }})
  #       [Manifest](${{ steps.manifest.outputs.manifest_url }})
  #       [Checksum](${{ steps.manifest.outputs.checksum_url }})
