name: PrintNanny OS Base
on:
  workflow_dispatch:
    inputs:
      dryrun:
        description: 'Dry run: false|true'    
        required: true
        default: 'false'
jobs:
  build-printnanny-os:
    strategy:
      matrix:
        os: [  bullseye ]
        arch: [ arm64 ]
        platform: [ debian ]
        variant: [ desktop, slim ]
        include:
          - image_name: printnanny-os-desktop-bullseye-arm64
            ansible_playbook: ./playbooks/printnanny/desktop.yml
            ansible_extra_vars: vars/generic-pi-arm64.ansiblevars.yml
            packer_template_file: templates/generic-pi.pkr.hcl
            packer_var_file: vars/printnanny-pi-arm64.pkrvars.hcl
            arch: arm64
            os: bullseye
            platform: debian
            variant: desktop
          - image_name: printnanny-os-slim-bullseye-arm64
            ansible_playbook: ./playbooks/printnanny/slim.yml
            ansible_extra_vars: vars/generic-pi-arm64.ansiblevars.yml
            packer_template_file: templates/generic-pi.pkr.hcl
            packer_var_file: vars/printnanny-pi-arm64.pkrvars.hcl
            arch: arm64
            os: bullseye
            platform: debian
            variant: slim
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - id: build
        uses: ./.github/workflows/scripts/build
        with:
          image_name: ${{ matrix.image_name }}
          ansible_playbook: ${{ matrix.ansible_playbook }}
          ansible_extra_vars: ${{ matrix.ansible_extra_vars }}
          packer_var_file: ${{ matrix.packer_var_file }}
          packer_template_file: ${{ matrix.packer_template_file }}
          gpg_sign_key: ${{ secrets.PRINTNANNY_GPG_PRIVATE_KEY }}
          gpg_passphrase: ${{ secrets.PRINTNANNY_GPG_PASSPHRASE }}
          dryrun: ${{ github.event.inputs.dryrun }}
      - name: Trigger downstream image builds
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: PrintNanny OS Variants
          token: ${{ secrets.REPO_GITHUB_TOKEN }}
      - name: Publish image
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Publish Image
          token: ${{ secrets.REPO_GITHUB_TOKEN }}
          inputs: '{ "artifact": "{{ steps.build.outputs.artifact }}", "path": "${{ steps.build.outputs.image_path }}", "workflow": "build-printnanny-base.yml" }'
