on: 
  push:
    branches: [ main, devel ]
  pull_request:
    branches: [ main, devel ]
jobs:
  packer-validate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout branch
      uses: actions/checkout@v2
    - run: |
        make validate
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
      with:
       scandir: './tools'