on: 
  push:
    branches: [ main, devel ]
  pull_request:
    branches: [ main, devel ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout branch
      uses: actions/checkout@v2
    - uses: satackey/action-docker-layer-caching@v0.0.11
      # Ignore the failure of a step and avoid terminating the job.
      continue-on-error: true
    - run: make validate
