on: 
  push:
    branches: [ main, devel ]
  pull_request:
    branches: [ main, devel ]
env:
  GCP_SERVICE_ACCOUNT: ${{ secrets.PACKER_SERVICE_ACCOUNT_KEY }}
  GCP_BUCKET: print-nanny-cdn
  CPU_ARCH: arm64
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout branch
      uses: actions/checkout@v2
    - run: make validate
