on: 
  push:
    branches: [ main, devel ]
  pull_request:
    branches: [ main, devel ]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout branch
      uses: actions/checkout@v2
    - run: make validate
