on: 
  push:
    branches: [ main, devel ]
  pull_request:
    branches: [ main, devel ]
jobs:
  lint:
    strategy:
      # fail-fast: false # if fail-fast is true (default) parallel builds will be cancelled on first matrix failure
      matrix:
        image:
          - generic-pi-buster-arm64
          - generic-pi-bullseye-arm64
        include:
          - image: generic-pi-buster-arm64
            template_file: templates/generic-pi.pkr.hcl
            packer_var_file: vars/generic-pi-buster-arm64.pkrvars.hcl
            ansible_extra_vars: vars/generic-pi-arm64.ansiblevars.yml

          - image: generic-pi-bullseye-arm64
            template_file: templates/generic-pi.pkr.hcl
            packer_var_file: vars/generic-pi-bullseye-arm64.pkrvars.hcl
            ansible_extra_vars: vars/generic-pi-arm64.ansiblevars.yml

    runs-on: ubuntu-latest
    steps:
    - name: Checkout branch
      uses: actions/checkout@v2
    - name: Ensure ansible variables file generated
      run: make ${{ matrix.ansible_extra_vars }}
    - run: |
        make validate2 \
          PACKER_VAR_FILE=${{ matrix.packer_var_file }} \
          IMAGE_NAME=${{ matrix.image_name }} \
          PACKER_TEMPLATE_FILE=${{ matrix.template_file }} \
          ANSIBLE_EXTRA_VARS=${{ matrix.ansible_extra_vars }}
