# bake a nightly image
on:
  # on manual trigger (packer repo) OR workflow_dispatch event from another repo's cd pipeline
  # https://github.community/t/triggering-by-other-repository/16163/6
  workflow_dispatch:
    inputs:
      # begin BASE_IMAGE
      BASE_DISTRO_VERSION:
        description: 'Version string for base distribution, e.g. 2021-05-07-raspios-buster-arm64 or 20211019-02:17-debian-bullseye-arm64'
        required: true
        default: '2021-05-07-raspios-buster-arm64'
      BASE_IMAGE_URL:
        description: 'Bake nightly beginning from this base image'
        required: true
        default: 'https://downloads.raspberrypi.org/raspios_arm64/images/raspios_arm64-2021-05-28/2021-05-07-raspios-buster-arm64.zip'
      BASE_IMAGE_CHECKSUM:
        required: true
        description: 'Checksum for base image'
        default: 'https://downloads.raspberrypi.org/raspios_arm64/images/raspios_arm64-2021-05-28/2021-05-07-raspios-buster-arm64.zip.sha256'
      # end BASE_IMAGE
      # begin app vars
      PRINTNANNY_CLI_VERSION:
        description: 'https://github.com/bitsy-ai/print-nanny-cli/releases'
        required: true
        default: '0.1.3'
      OCTOPRINT_VERSION:
        description: 'https://github.com/OctoPrint/OctoPrint/releases'
        required: true
        default: '1.6.1'
      JANUS_VERSION:
        description: 'https://github.com/meetecho/janus-gateway/releases'
        default: 'v0.11.5'
        required: true
      RELEASE_CHANNEL:
        description: 'Publish image to release channel: (nightly, stable)'     
        required: true
        default: 'nightly'
    
    
env:
  GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.PACKER_SERVICE_ACCOUNT_KEY }}
  GCP_SERVICE_ACCOUNT: ${{ secrets.PACKER_SERVICE_ACCOUNT }}
  GCP_BUCKET: print-nanny-cdn

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Install platform deps
      run: sudo apt-get install -y jq
    - name: Checkout branch
      uses: actions/checkout@v2
    - name: Write deploy key
      run: echo $GCP_SERVICE_ACCOUNT_KEY > key.json
    - name: Active Service Account
      run: gcloud auth activate-service-account $GCP_SERVICE_ACCOUNT --key-file=key.json
    - name: Make base image
      id: packer
      run: |
        make dist/printnanny-pi.img \
          BASE_DISTRO_VERSION=${{ github.event.inputs.BASE_DISTRO_VERSION }} \
          BASE_IMAGE_CHECKSUM=${{ github.event.inputs.BASE_IMAGE_CHECKSUM }} \
          BASE_IMAGE_URL=${{ github.event.inputs.BASE_IMAGE_URL }} \
          PRINTNANNY_CLI_VERSION=${{ github.event.inputs.PRINTNANNY_CLI_VERSION }} \
          OCTOPRINT_VERSION=${{ github.event.inputs.OCTOPRINT_VERSION }} \
          JANUS_VERSION=${{ github.event.inputs.JANUS_VERSION }} \
          RELEASE_CHANNEL=${{ github.event.inputs.RELEASE_CHANNEL }}
        echo ::set-output name=image_path::"$(cat dist/manifest.json | jq '.builds[-1].custom_data.image_path')"
        echo ::set-output name=image_name::"$(cat dist/manifest.json | jq '.builds[-1].custom_data.image_name')"
        echo ::set-output name=checksum::"$(cat dist/sha256.checksum)"
    - name: Upload to GCP_BUCKET
      run: |
        gsutil rsync -r dist/ gs://$GCP_BUCKET/${{ steps.packer.outputs.image_path }}/
    - name: Send Discord notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.PRINT_NANNY_DISCORD_DEPLOY_WEBHOOK }}
      uses: Ilshidur/action-discord@master
      with:
        args: |
          Published https://cdn.print-nanny.com/${{ steps.packer.outputs.image_path }}/${{ steps.packer.outputs.image_name }}
          Checksum https://cdn.print-nanny.com/${{ steps.packer.outputs.image_path }}/sha256.checksum
          Manifest https://cdn.print-nanny.com/${{ steps.packer.outputs.image_path }}/manifest.json
          ```
          ${{ steps.packer.outputs.checksum }}
          ------------------------------------
          BASE_DISTRO_VERSION = ${{ github.event.inputs.BASE_DISTRO_VERSION }}
          PRINTNANNY_CLI_VERSION = ${{ github.event.inputs.PRINTNANNY_CLI_VERSION }}
          OCTOPRINT_VERSION=${{ github.event.inputs.OCTOPRINT_VERSION }}
          JANUS_VERSION=${{ github.event.inputs.JANUS_VERSION }}
          ```