on:
  workflow_dispatch:
    inputs:
      RELEASE_CHANNEL:
        description: 'Publish image to release channel: (nightly, stable)'     
        required: true
        default: 'nightly'
env:
  GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.PACKER_SERVICE_ACCOUNT_KEY }}
  GCP_SERVICE_ACCOUNT: ${{ secrets.PACKER_SERVICE_ACCOUNT }}
  GCP_BUCKET: print-nanny-cdn
  CDN_BASE_URL: https://cdn.print-nanny.com
jobs:

###
# begin printnanny base image jobs
###
  build-printnanny-os:
    strategy:
      fail-fast: false
      matrix:
        os: [  bullseye ]
        arch: [ arm64 ]
        platform: [ debian ]
        include:
          - image_name: printnanny-os-bullseye-arm64
            ansible_extra_vars: vars/printnanny-pi-arm64.ansiblevars.json
            packer_template_file: templates/generic-pi.pkr.hcl
            packer_var_file: vars/printnanny-pi-arm64.pkrvars.hcl
            arch: arm64
            os: bullseye
            platform: debian
    runs-on: ubuntu-latest
    steps:
    - name: Checkout branch
      uses: actions/checkout@v2
    - id: build
      uses: ./.github/workflows/scripts/build
      with:
        IMAGE_NAME: ${{ matrix.image_name }}
        ANSIBLE_EXTRA_VARS: ${{ matrix.ansible_extra_vars }}
        PACKER_VAR_FILE: ${{ matrix.packer_var_file }}
        PACKER_TEMPLATE_FILE: ${{ matrix.packer_template_file }}

  nightly-printnanny-os:
    environment: nightly
    needs: [ build-printnanny-os ]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image_name:
          - printnanny-os-bullseye-arm64
    steps:
    - name: Checkout branch
      uses: actions/checkout@v2
    - id: publish-nightly
      uses: ./.github/workflows/scripts/publish-nightly
      with:
        IMAGE_NAME: ${{ matrix.image_name }}
        DISCORD_WEBHOOK: ${{ secrets.PRINT_NANNY_DISCORD_DEPLOY_WEBHOOK }}
    
  stable-printnanny-os:
    # comment to require manual approval before publishing
    environment: stable
    needs: [ nightly-printnanny-os ]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image_name:
          - printnanny-os-bullseye-arm64
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - id: publish-stable
        uses: ./.github/workflows/scripts/publish-stable
        with:
          IMAGE_NAME: ${{ matrix.image_name }}
          DISCORD_WEBHOOK: ${{ secrets.PRINT_NANNY_DISCORD_DEPLOY_WEBHOOK }}