on:
  workflow_dispatch:
    inputs:
      RELEASE_CHANNEL:
        description: 'Publish image to release channel: (nightly, stable)'     
        required: true
        default: 'nightly'
env:
  GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.PACKER_SERVICE_ACCOUNT_KEY }}
  GCP_SERVICE_ACCOUNT: ${{ secrets.PACKER_SERVICE_ACCOUNT }}
  GCP_BUCKET: print-nanny-cdn
  CDN_BASE_URL: https://cdn.print-nanny.com
jobs:
  # begin image job
  image:
    strategy:
      fail-fast: false
      matrix:
        os: [ bullseye ]
        arch: [ arm64 ]
        include:
          # - image_name: printnanny-base-buster-arm64
          #   base_image: generic-pi-buster-arm64
          #   template_file: templates/generic-pi.pkr.hcl
          #   packer_var_file: vars/printnanny-pi-arm64.pkrvars.hcl
          #   ansible_extra_vars: vars/printnanny-pi-arm64.ansiblevars.json
          #   arch: arm64
          #   os: buster
          #   platform: debian

          - image_name: printnanny-base-bullseye-arm64
            base_image: generic-pi-bullseye-arm64
            template_file: templates/generic-pi.pkr.hcl
            packer_var_file: vars/printnanny-pi-arm64.pkrvars.hcl
            ansible_extra_vars: vars/printnanny-pi-arm64.ansiblevars.json
            arch: arm64
            os: bullseye
            platform: debian

    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: generic-pi.yml
          workflow_conclusion: success
          name: ${{ matrix.base_image }}-env
          path: env/
      - name: Ensure ansible_extra_vars on disk
        run: make ${{ matrix.ansible_extra_vars }}
      - name: Print vars (debug)
        run: |
          cat ${{ matrix.ansible_extra_vars }}
          cat env/${{ matrix.base_image }}.env
      - name: Make base image
        id: packer
        run: |
          make dist/${{ matrix.image_name}}.img \
            PACKER_VAR_FILE=${{ matrix.packer_var_file }} \
            RELEASE_CHANNEL=${{ github.event.inputs.RELEASE_CHANNEL }} \
            IMAGE_NAME=${{ matrix.image_name}} \
            PACKER_TEMPLATE_FILE=${{ matrix.template_file }} \
            ANSIBLE_EXTRA_VARS=${{ matrix.ansible_extra_vars }} \
            ENV_FILE=env/${{ matrix.base_image }}.env \
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.image_name }}-dist
          path: dist/
  # end image job
  # begin publish job
  publish-nightly:
    # github action inputs are always strings
    environment: nightly
    needs: [image]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image_name:
          # - printnanny-base-buster-arm64
          - printnanny-base-bullseye-arm64
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: ${{ matrix.image_name }}-dist
          path: dist/
          if-no-files-found: error
      - name: Create environment artifacts
        id: packer
        run: |
          ./tools/manifest-to-env.sh
          . env/${{ matrix.image_name }}.sh
          echo ::set-output name=image_stamp::"$IMAGE_STAMP"
          echo ::set-output name=image_path::"$IMAGE_PATH"
          echo ::set-output name=image_url::"$IMAGE_URL"
          echo ::set-output name=checksum_url::"$CHECKSUM_URL"
          echo ::set-output name=manifest_url::"$MANIFEST_URL"
      - name: Send Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.PRINT_NANNY_DISCORD_DEPLOY_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: |
            🧪 NEW nightly `${{ steps.packer.outputs.image_stamp }}`
            ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
  publish-stable:
    # github action inputs are always strings
    environment: stable
    needs: [image, publish-nightly]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image_name:
          # - printnanny-base-buster-arm64
          - printnanny-base-bullseye-arm64
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: ${{ matrix.image_name }}-dist
          path: dist/
      - name: Write deploy key
        run: echo $GCP_SERVICE_ACCOUNT_KEY > key.json
      - name: Activate Service Account
        run: gcloud auth activate-service-account $GCP_SERVICE_ACCOUNT --key-file=key.json
      # packer-builder-arm does not support file:// URI
      # so downstream builds must consume https://cdn url
      - name: Create environment artifacts
        id: packer
        run: |
          ./tools/manifest-to-env.sh
          . env/${{ matrix.image_name }}.sh
          echo ::set-output name=image_stamp::"$IMAGE_STAMP"
          echo ::set-output name=image_path::"$IMAGE_PATH"
          echo ::set-output name=image_url::"$IMAGE_URL"
          echo ::set-output name=checksum_url::"$CHECKSUM_URL"
          echo ::set-output name=manifest_url::"$MANIFEST_URL"

      # retain published urls as artifacts in published/ namespace
      # intended for use with: https://github.com/dawidd6/action-download-artifact
      # packer-builder-arm does not support file:// uri, so published cdn urls must be passed in addition to artifact files
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.image_name }}-published
          path: published/
      - name: Upload to GCP_BUCKET
        run: |
          gsutil rsync -r dist/ gs://$GCP_BUCKET/${{ steps.artifact.outputs.image_path }}/
      - name: Send Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.PRINT_NANNY_DISCORD_DEPLOY_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: |
            🚀 Published `${{ steps.packer.outputs.image_stamp }}`
            [Download](${{ steps.packer.outputs.image_url }})
            [Manifest](${{ steps.packer.outputs.manifest_url }})
            [Checksum](${{ steps.packer.outputs.checksum_url }})
