name: Publish Image
on:
  workflow_dispatch:
    inputs:
      artifact:
        description: 'Name of artifact to download'    
        required: true
      bucket:
        description: 'Destination bucket'
        default: 'printnanny-downloads'
        required: true
      path:
        description: 'Upload path (without bucket name)'
        required: true

env:
  GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.PACKER_SERVICE_ACCOUNT_KEY }}
  GCP_SERVICE_ACCOUNT: ${{ secrets.PACKER_SERVICE_ACCOUNT }}
  GCP_BUCKET: printnanny-downloads
jobs:
  publish:
    strategy:
      matrix:
        artifact:
          - printnanny-os-desktop-bullseye-arm64
          - printnanny-os-slim-bullseye-arm64
          - printnanny-os-desktop-bullseye-arm64-octprint
          - printnanny-os-slim-bullseye-arm64-octoprint
        include:
          - artifact: printnanny-os-desktop-bullseye-arm64
            variant: base_desktop
          - artifact: printnanny-os-slim-bullseye-arm64
            variant: slim_desktop
          - artifact: printnanny-os-desktop-bullseye-arm64-octoprint
            variant: base_desktop
          - artifact: printnanny-os-slim-bullseye-arm64-octoprint
            variant: slim_desktop
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build-printnanny.yml
          workflow_conclusion: success
      - name: Publish artifact to downloads.print-nanny.com
        id: publish
        uses: ./.github/workflows/scripts/cdn-upload
        with:
          DISCORD_WEBHOOK: ''
          IMAGE_NAME: ${{ matrix.artifact }}
          PRINTNANNY_API_TOKEN: ${{ secrets.PROD_RELEASE_SERVICE_TOKEN }}
          IMAGE_VARIANT: ${{ matrix.variant }}