on:
  workflow_dispatch:
    inputs:
      RELEASE_CHANNEL:
        description: 'Publish image to release channel: (nightly, stable)'     
        required: true
        default: 'nightly'
        
env:
  GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.PACKER_SERVICE_ACCOUNT_KEY }}
  GCP_SERVICE_ACCOUNT: ${{ secrets.PACKER_SERVICE_ACCOUNT }}
  GCP_BUCKET: print-nanny-cdn
  CDN_BASE_URL: https://cdn.print-nanny.com

jobs:
  # begin image job
  generic-base-image:
    strategy:
      fail-fast: false
      matrix:
        os: [  bullseye ]
        arch: [ arm64 ]
        platform: [ debian ]
        include:
          # uncomment + edit to build additional os, arch, platform variants
          # - image_name: generic-pi-buster-arm64
          #   base_image: 2021-05-07-raspios-buster-arm64
          #   packer_template_file: templates/generic-pi.pkr.hcl
          #   packer_var_file: vars/generic-pi-buster-arm64.pkrvars.hcl
          #   ansible_extra_vars: vars/generic-pi-arm64.ansiblevars.yml
          #   arch: arm64
          #   os: buster
          #   platform: debian

          - image_name: generic-pi-bullseye-arm64
            base_image: 2021-10-30-raspios-bullseye-arm64
            packer_template_file: templates/generic-pi.pkr.hcl
            packer_var_file: vars/generic-pi-bullseye-arm64.pkrvars.hcl
            ansible_extra_vars: vars/generic-pi-arm64.ansiblevars.yml
            arch: arm64
            os: bullseye
            platform: debian

    runs-on: ubuntu-latest
    steps:
    - name: Checkout branch
      uses: actions/checkout@v2
    - id: build
      uses: ./actions/build@main
      with:
        RELEASE_CHANNEL: ${{ inputs.RELEASE_CHANNEL }}
        IMAGE_NAME: ${{ matrix.image_name }}
        ANSIBLE_EXTRA_VARS: ${{ matrix.ansible_extra_vars }}
        PACKER_VAR_FILE: ${{ matrix.packer_var_file }}
        PACKER_TEMPLATE_FILE: ${{ matrix.packer_template_file}}
        
  # end base image job
  # begin base image publish job
  publish-generic-base-image-nightly:
    # github action inputs are always strings
    environment: nightly
    needs: [ generic-base-image ]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image_name:
          # - generic-pi-buster-arm64
          - generic-pi-bullseye-arm64
    steps:
    - id: publish-nightly
      uses: ./actions/publish-nightly@main
      with:
        RELEASE_CHANNEL: ${{ inputs.RELEASE_CHANNEL }}
        IMAGE_NAME: ${{ matrix.image_name }}
        ARTIFACT:  ${{ needs.jobs.base-image.outputs.artifact }}
        DEPLOY_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_DEPLOYS_PRIVATE }}
    
  publish-generic-base-image-stable:
    # comment to require manual approval before publishing
    # environment: stable
    needs: [generic-base-image, publish-generic-base-image-nightly]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image_name:
          # - generic-pi-buster-arm64
          - generic-pi-bullseye-arm64
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
