# bake a nightly image
on:
  # on manual trigger (packer repo) OR workflow_dispatch event from another repo's cd pipeline
  # https://github.community/t/triggering-by-other-repository/16163/6
  workflow_dispatch:
    inputs:
      RELEASE_CHANNEL:
        description: 'Publish image to release channel: (nightly, stable)'     
        required: true
        default: 'nightly'
    
env:
  GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.PACKER_SERVICE_ACCOUNT_KEY }}
  GCP_SERVICE_ACCOUNT: ${{ secrets.PACKER_SERVICE_ACCOUNT }}
  GCP_BUCKET: print-nanny-cdn

jobs:
  publish:
    strategy:
      # fail-fast: false # if fail-fast is true (default) parallel builds will be cancelled on first matrix failure
      matrix:
        image_name:
          - printnanny-pi-buster-arm64
          - generic-pi-buster-arm64
        include:
          - image_name: printnanny-pi-buster-arm64
            template_file: templates/generic-pi.pkr.hcl
            var_file: vars/printnanny-pi-buster-arm64.pkrvars.hcl
            ansible_extra_vars: vars/printnanny-pi-buster-arm64.ansiblevars.json
            discord_webhook: ${{ secrets.PRINT_NANNY_DISCORD_DEPLOY_WEBHOOK }}
          - image_name: generic-pi-buster-arm64
            template_file: templates/generic-pi.pkr.hcl
            var_file: vars/generic-pi-buster-arm64.pkrvars.hcl
            ansible_extra_vars: vars/generic-pi-buster-arm64.ansiblevars.yml
            discord_webhook: ${{ secrets.DISCORD_WEBHOOK_DEPLOYS_PRIVATE }}
    runs-on: ubuntu-latest
    steps:
    - name: Install platform deps
      run: sudo apt-get install -y jq wget
    - name: Checkout branch
      uses: actions/checkout@v2
    - name: Write deploy key
      run: echo $GCP_SERVICE_ACCOUNT_KEY > key.json
    - name: Active Service Account
      run: gcloud auth activate-service-account $GCP_SERVICE_ACCOUNT --key-file=key.json
    - name: Download ansible_extra_vars
      run: make ${{ matrix.ansible_extra_vars }}
    - name: Make base image
      id: packer
      run: |
        make dist/${{ matrix.image_name}}.img \
          VAR_FILE=${{ matrix.var_file }} \
          RELEASE_CHANNEL=${{ github.event.inputs.RELEASE_CHANNEL }} \
          IMAGE_NAME=${{ matrix.image_name}} \
          TEMPLATE_FILE=${{ matrix.template_file }}
          ANSIBLE_EXTRA_VARS=${{ matrix.ansible_extra_vars }}

        echo ::set-output name=image_path::"$(cat dist/manifest.json | jq '.builds[-1].custom_data.image_path')"
        echo ::set-output name=image_name::"$(cat dist/manifest.json | jq '.builds[-1].custom_data.image_name')"
        echo ::set-output name=checksum::"$(cat dist/sha256.checksum)"
        echo ::set-output name=ansible_extra_vars::"$(cat matrix.ansible_extra_vars)"

    - name: Upload to GCP_BUCKET
      run: |
        gsutil rsync -r dist/ gs://$GCP_BUCKET/${{ steps.packer.outputs.image_path }}/
    - name: Send Discord notification
      env:
        DISCORD_WEBHOOK: ${{ matrix.discord_webhook }}
      uses: Ilshidur/action-discord@master
      with:
        args: |
          Published https://cdn.print-nanny.com/${{ steps.packer.outputs.image_path }}/${{ steps.packer.outputs.image_name }}
          Checksum https://cdn.print-nanny.com/${{ steps.packer.outputs.image_path }}/sha256.checksum
          Build manifest https://cdn.print-nanny.com/${{ steps.packer.outputs.image_path }}/manifest.json
          ```
          ${{ steps.packer.outputs.checksum }}
          ------------------------------------
          ${{ steps.packer.outputs.ansible_extra_vars }}
          ```