on: 
  push:
    branches: [ main, devel ]

env:
  GCP_SERVICE_ACCOUNT: ${{ secrets.PACKER_SERVICE_ACCOUNT_KEY }}
  GCP_BUCKET: print-nanny-cdn
  CPU_ARCH: arm64
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Input Settings
    - name: Checkout branch
      uses: actions/checkout@v2
    - uses: satackey/action-docker-layer-caching@v0.0.11
      # Ignore the failure of a step and avoid terminating the job.
      continue-on-error: true
    - name: Write deploy key
      run: echo $GCP_SERVICE_ACCOUNT_KEY > key.json
    - name: Active Service Account
      run: gcloud auth activate-service-account $GCP_SERVICE_ACCOUNT --key-file=key.json
    - name: Make base image
      run: make image RELEASE_CHANNEL=main CPU_ARCH=$CPU_ARCH
    - name: Print Manifest
      id: manifest
      run: cat dist/manifest.json
    - name: Upload to GCP_BUCKET
      run: |
        gsutil cp -r dist/ gs://$GCP_BUCKET/releases/main/{{ steps.manifest.outputs.custom_data.image_path }}/{{ steps.manifest.outputs.custom_data.image_name }}/

    - name: Send Discord notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.PRINT_NANNY_DISCORD_DEPLOY_WEBHOOK }}
      uses: Ilshidur/action-discord@master
      with:
        args: 'Published img from {{ EVENT_PAYLOAD.repository.full_name }}@{{ GITHUB_SHA }} \n {{ steps.manifest.outputs }}'
