on:
  workflow_dispatch:
    inputs:
      RELEASE_CHANNEL:
        description: 'Publish image to release channel: (nightly, stable)'     
        required: true
        default: 'nightly'
        
env:
  GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.PACKER_SERVICE_ACCOUNT_KEY }}
  GCP_SERVICE_ACCOUNT: ${{ secrets.PACKER_SERVICE_ACCOUNT }}
  GCP_BUCKET: print-nanny-cdn
  CDN_BASE_URL: https://cdn.print-nanny.com

jobs:
##
# begin generic image jobs
##
  build-generic-image:
    strategy:
      fail-fast: false
      matrix:
        os: [  bullseye ]
        arch: [ arm64 ]
        platform: [ debian ]
        include:
          - image_name: generic-pi-bullseye-arm64
            ansible_extra_vars: vars/generic-pi-arm64.ansiblevars.yml
            packer_env_file: vars/generic.env # empty in base image (no dynamic env vars)
            packer_template_file: templates/generic-pi.pkr.hcl
            packer_var_file: vars/generic-pi-bullseye-arm64.pkrvars.hcl
            arch: arm64
            os: bullseye
            platform: debian
    outputs:
      artifact: ${{ matrix.image_name }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout branch
      uses: actions/checkout@v2
    - id: build
      uses: ./.github/workflows/scripts/build
      with:
        ANSIBLE_EXTRA_VARS: ${{ matrix.ansible_extra_vars }}
        IMAGE_NAME: ${{ matrix.image_name }}
        RELEASE_CHANNEL: ${{ inputs.RELEASE_CHANNEL }}
        PACKER_ENV_FILE: ${{ matrix.PACKER_ENV_FILE }}
        PACKER_VAR_FILE: ${{ matrix.packer_var_file }}
        PACKER_TEMPLATE_FILE: ${{ matrix.packer_template_file}}


  publish-generic-nightly:
    # github action inputs are always strings
    environment: nightly
    needs: [ build-generic-image]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image_name:
          - generic-pi-bullseye-arm64
    steps:
    - name: Checkout branch
      uses: actions/checkout@v2
    - id: publish-nightly
      uses: ./.github/workflows/scripts/publish-nightly
      with:
        IMAGE_NAME: ${{ matrix.image_name }}
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_DEPLOYS_PRIVATE }}
    
  publish-generic-stable:
    # comment to require manual approval before publishing
    # environment: stable
    needs: [build-generic-image, publish-generic-nightly]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image_name:
          - generic-pi-bullseye-arm64
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - id: publish-stable
        uses: ./.github/workflows/scripts/publish-stable
        with:
          IMAGE_NAME: ${{ matrix.image_name }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_DEPLOYS_PRIVATE }}

###
# begin printnanny base image jobs
###
  build-printnanny-os:
    needs: [build-generic-image]
    strategy:
      fail-fast: false
      matrix:
        os: [  bullseye ]
        arch: [ arm64 ]
        platform: [ debian ]
        include:
          - image_name: printnanny-os-bullseye-arm64
            base_image: generic-pi-bullseye-arm64
            ansible_extra_vars: vars/printnanny-pi-arm64.ansiblevars.json
            packer_template_file: templates/generic-pi.pkr.hcl
            packer_var_file: vars/printnanny-pi-arm64.pkrvars.hcl
            arch: arm64
            os: bullseye
            platform: debian
    runs-on: ubuntu-latest
    steps:
    - name: Checkout branch
      uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
      with:
        name: ${{ matrix.base_image }}
        path: dist
    - id: build
      uses: ./.github/workflows/scripts/build
      with:
        ANSIBLE_EXTRA_VARS: ${{ matrix.ansible_extra_vars }}
        IMAGE_NAME: ${{ matrix.image_name }}
        RELEASE_CHANNEL: ${{ inputs.RELEASE_CHANNEL }}
        PACKER_ENV_FILE: dist/${{ matrix.base_image }}.pkr.env
        PACKER_VAR_FILE: ${{ matrix.packer_var_file }}
        PACKER_TEMPLATE_FILE: ${{ matrix.packer_template_file}}
###
# begin printnanny octoprint jobs
###
  build-printnanny-octoprint:
    needs: [build-generic-image, build-printnanny-os ]
    strategy:
      fail-fast: false
      matrix:
        os: [  bullseye ]
        arch: [ arm64 ]
        platform: [ debian ]
        include:
          # uncomment + edit to build additional os, arch, platform variants
          # - image_name: generic-pi-buster-arm64
          #   base_image: 2021-05-07-raspios-buster-arm64
          #   packer_template_file: templates/generic-pi.pkr.hcl
          #   packer_var_file: vars/generic-pi-buster-arm64.pkrvars.hcl
          #   ansible_extra_vars: vars/generic-pi-arm64.ansiblevars.yml
          #   arch: arm64
          #   os: buster
          #   platform: debian

          - image_name: printnanny-os-octoprint-bullseye-arm64
            packer_template_file: templates/generic-pi.pkr.hcl
            packer_var_file: vars/octoprint-pi-arm64.pkrvars.hcl
            ansible_extra_vars: vars/octoprint-pi-arm64.ansiblevars.json
            arch: arm64
            os: bullseye
            platform: debian
    outputs:
      artifact: ${{ steps.build.outputs.artifact }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout branch
      uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
      with:
        name: ${{ matrix.base_image }}
        path: dist
    - id: build
      uses: ./.github/workflows/scripts/build
      with:
        ANSIBLE_EXTRA_VARS: ${{ matrix.ansible_extra_vars }}
        IMAGE_NAME: ${{ matrix.image_name }}
        RELEASE_CHANNEL: ${{ inputs.RELEASE_CHANNEL }}
        PACKER_ENV_FILE: dist/${{ matrix.base_image }}.pkr.env
        PACKER_VAR_FILE: ${{ matrix.packer_var_file }}
        PACKER_TEMPLATE_FILE: ${{ matrix.packer_template_file }}

  nightly-printnanny-octoprint:
    # github action inputs are always strings
    environment: nightly
    needs: [ build-printnanny-octoprint]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image_name:
          - printnanny-os-octoprint-bullseye-arm64
    steps:
    - name: Checkout branch
      uses: actions/checkout@v2
    - id: publish-nightly
      uses: ./.github/workflows/scripts/publish-nightly
      with:
        IMAGE_NAME: ${{ matrix.image_name }}
        DISCORD_WEBHOOK: ${{ secrets.PRINT_NANNY_DISCORD_DEPLOY_WEBHOOK }}
    
  stable-printnanny-octoprint:
    # comment to require manual approval before publishing
    environment: stable
    needs: [ build-printnanny-octoprint, nightly-printnanny-octoprint ]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image_name:
          - printnanny-os-octoprint-bullseye-arm64
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - id: publish-stable
        uses: ./.github/workflows/scripts/publish-stable
        with:
          IMAGE_NAME: ${{ matrix.image_name }}
          DISCORD_WEBHOOK: ${{ secrets.PRINT_NANNY_DISCORD_DEPLOY_WEBHOOK }}