name: Debian Slim
on:
  workflow_dispatch:

env:
  GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.PACKER_SERVICE_ACCOUNT_KEY }}
  GCP_SERVICE_ACCOUNT: ${{ secrets.PACKER_SERVICE_ACCOUNT }}
  GCP_BUCKET: print-nanny-cdn
  CDN_BASE_URL: https://cdn.print-nanny.com

jobs:
##
# begin generic image jobs
##
  build-generic-image:
    strategy:
      fail-fast: false
      matrix:
        os: [  bullseye ]
        arch: [ arm64 ]
        platform: [ debian ]
        include:
          - image_name: raspios-bullseye-slim-arm64
            ansible_extra_vars: vars/generic-pi-arm64.ansiblevars.yml
            arch: arm64
            os: bullseye
            platform: debian
    outputs:
      artifact: ${{ matrix.image_name }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout branch
      uses: actions/checkout@v2
    - id: base
      uses: ./.github/workflows/scripts/build
      with:
        ANSIBLE_EXTRA_VARS: ${{ matrix.ansible_extra_vars }}
        IMAGE_NAME: ${{ matrix.image_name }}
        PACKER_VAR_FILE: vars/generic-pi-bullseye-arm64.pkrvars.hcl
        PACKER_TEMPLATE_FILE: templates/slim-base.pkr.hcl
    - id: slim
      uses: ./.github/workflows/scripts/build
      with:
        ANSIBLE_EXTRA_VARS: ${{ matrix.ansible_extra_vars }}
        IMAGE_NAME: ${{ matrix.image_name }}
        PACKER_VAR_FILE: vars/slim-bullseye-arm64.pkrvars.hcl
        PACKER_TEMPLATE_FILE: templates/slim-base.pkr.hcl
    - id: publish-stable
      uses: ./.github/workflows/scripts/publish-stable
      with:
        DISCORD_WEBHOOK: ${{ secrets.PRINT_NANNY_DISCORD_DEPLOY_WEBHOOK }}